# Generated by Django 4.1 on 2023-10-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_quizresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_role',
            field=models.CharField(default='Data Annotation Specialist', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
