# Generated by Django 4.1 on 2023-10-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_quizresult_delete_quizresultlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuizResult',
        ),
    ]
