# Generated by Django 4.1 on 2023-10-23 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_quizquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.quizquestion')),
            ],
        ),
    ]
